### ISSUE TITLE
Doesn't download because of login errors

### ISSUE THREAD

**Issue by TEREREZZ** [h3llrais3r/Auto-Subliminal#274] opened 2020-01-18 12:19 UTC
### INFO

**Windows 10 1909**
**3.00**
**Git branch:**
**Git version:**
**Python 2.7.15**

I've been having this problem for months but it doesn't fix itself. I've tried selecting other subtitle providers, didn't help. Accounts are just fine on opensubtitles/addic7ed , they work, not banned or something. 

### ERROR
```
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\providers\addic7ed.py", line 115, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: RRRRR
2020-01-18 13:11:55,571 ERROR Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 72, in __getitem__
    provider.initialize()
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\providers\addic7ed.py", line 115, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: RRRRR
2020-01-18 13:11:56,655 ERROR Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 72, in __getitem__
    provider.initialize()
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\providers\addic7ed.py", line 115, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: RRRRR
2020-01-18 13:12:02,690 ERROR Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 72, in __getitem__
    provider.initialize()
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\providers\addic7ed.py", line 115, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: RRRRR
2020-01-18 13:12:03,335 ERROR Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 72, in __getitem__
    provider.initialize()
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\providers\addic7ed.py", line 115, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: RRRRR
2020-01-18 13:12:04,013 ERROR Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 72, in __getitem__
    provider.initialize()
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\providers\addic7ed.py", line 115, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: RRRRR
2020-01-18 13:12:04,612 ERROR Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 72, in __getitem__
    provider.initialize()
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\providers\addic7ed.py", line 115, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: RRRRR
2020-01-18 13:12:05,207 ERROR Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 72, in __getitem__
    provider.initialize()
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\providers\addic7ed.py", line 115, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: RRRRR
2020-01-18 13:12:05,801 ERROR Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 72, in __getitem__
    provider.initialize()
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\providers\addic7ed.py", line 115, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: RRRRR
2020-01-18 13:12:06,413 ERROR Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 72, in __getitem__
    provider.initialize()
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\providers\addic7ed.py", line 115, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: RRRRR
2020-01-18 13:12:07,105 ERROR Unexpected error in provider u'addic7ed'
Traceback (most recent call last):
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 134, in list_subtitles_provider
    return self[provider].list_subtitles(video, provider_languages)
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\core.py", line 72, in __getitem__
    provider.initialize()
  File "C:\Users\x\Desktop\Tools\-SubsDL\Auto-Subliminal-master nov 2019\lib\subliminal\providers\addic7ed.py", line 115, in initialize
    raise AuthenticationError(self.username)
AuthenticationError: RRRRR
127.0.0.1 - - [18/Jan/2020:13:12:10] "GET /home/ HTTP/1.1" 200 662526 "http://localhost:8083/home/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"
127.0.0.1 - - [18/Jan/2020:13:12:10] "GET /api/settings HTTP/1.1" 200 7090 "http://localhost:8083/home/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"
127.0.0.1 - - [18/Jan/2020:13:12:11] "GET /system/websocket HTTP/1.1" 101 - "" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36"

```

**Comment by h3llrais3r** [comment] 2020-01-21 15:46
Duplicate of https://github.com/h3llrais3r/Auto-Subliminal/issues/164.
Addic7ed has added captcha on the login... so we cannot use it anymore for now...

**Closed by h3llrais3r** 2020-01-21 15:46 UTC
