### ISSUE TITLE
Read imdb id from metadata file

### ISSUE THREAD

**Issue by Zeusy123** [h3llrais3r/Auto-Subliminal#18] opened 2017-12-06 19:00 UTC
Hi, i noticed a lot of movies, shows etc.. are not being idenfied correctly according to IMDB.
As mostl ibaries would have a metadata file in same folder as the source file, and named the same as source file, perhaps if you could grab the IMBD from that file instead???

source = Goodbye Berlin (2016)
metadata normally = Goodbye Berlin (2016).nfo
my metadata file = Goodbye Berlin (2016).xml

in both the IMDB value is in below content:
	<IMDB>tt4911940</IMDB>
	<IMDbId>tt4911940</IMDbId>
As you would also ensure your metadata is perfect:)

**Comment by h3llrais3r** [comment] 2017-12-06 19:07
Well, I never had problems with imd id's. Like explained in https://github.com/h3llrais3r/Auto-Subliminal/issues/17, I need a detailed debug log in order to investigate why imdb id is not properly retrieved.

**Comment by Zeusy123** [comment] 2017-12-06 19:14
I should explain to you I have a VERY large libary:) about 70TB in size, curently I'm just testing your script on movies (4k+) and added tvshows (36k+ eposides)

Im still waiting on the webpage opening, after I added more movies, so it working through each folder and I guess when its ocmpleted reading the folders, the webpage will open.  So I cant give you a details log at the moment, but I can paste to you mya capture of my dos window below:

2017-12-06 20:09:12,160 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:13,049 ERROR Imdb id not found for Killing Jesus (2015)
2017-12-06 20:09:17,535 ERROR Imdb id not found for Kim Dotcom, Caught in the (2017)
2017-12-06 20:09:18,332 ERROR Imdb id not found for Kind of Murder, A (2016)
2017-12-06 20:09:18,426 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:21,832 ERROR Imdb id not found for King Arthur, Excalibur Rising (2017)
2017-12-06 20:09:22,614 ERROR Imdb id not found for King Arthur, Legend of the Sword (2017)
2017-12-06 20:09:22,691 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:23,816 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:27,638 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:30,525 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:33,575 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:35,426 ERROR Imdb id not found for Kingsglaive, Final Fantasy XV (2016)
2017-12-06 20:09:36,302 ERROR Imdb id not found for Kingsman, The Secret Service (2015)
2017-12-06 20:09:36,381 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:37,647 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:38,707 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:40,161 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:40,990 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:41,802 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:44,599 ERROR Imdb id not found for Knock Knock (2015)
2017-12-06 20:09:45,851 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:47,184 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:49,533 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:51,898 ERROR Imdb id not found for Kong, Skull Island (2017)
2017-12-06 20:09:52,006 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:55,088 ERROR Imdb id not found for Krampus (2015)
2017-12-06 20:09:56,878 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:57,697 ERROR Imdb id not found for Kronk's New Groove (2005)
2017-12-06 20:09:57,806 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:09:58,956 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:10:02,232 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:10:02,950 ERROR Imdb id not found for Kung Fu Jungle (2014)
2017-12-06 20:10:06,835 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:10:08,894 ERROR Imdb id not found for Kung Fu Panda Holiday (2010)
2017-12-06 20:10:09,950 ERROR Imdb id not found for Kung Fu Panda, Secrets of the Furious Five (2008)
2017-12-06 20:10:10,107 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:10:10,809 ERROR Imdb id not found for Kung Fu Panda, Secrets of the Masters (2011)
2017-12-06 20:10:11,825 ERROR Imdb id not found for Kung Fu Panda, Secrets of the Scroll (2016)
2017-12-06 20:10:15,200 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:10:16,848 ERROR Imdb id not found for L A Confidential (1997)
2017-12-06 20:10:18,509 ERROR Embedded subtitle track name u'Web (en)' is not a valid language
2017-12-06 20:10:20,026 ERROR Imdb id not found for La La Land (2016)
2017-12-06 20:10:25,223 ERROR Imdb id not found for Lady and the Tramp (1955)
2017-12-06 20:10:26,540 ERROR Imdb id not found for Lady and the Tramp 2, Scamp's Adventure (2001)

As you can see many have error imdb not found:-/ Hense why I sujested reading metadata:)

**Comment by h3llrais3r** [comment] 2017-12-06 19:15
Can you give me an example of a filename for which no imdb id is found?

**Comment by Zeusy123** [comment] 2017-12-06 19:25
La La Land (2016).mkv 
As u can see from log above (3rd line from bottom)
2017-12-06 20:10:20,026 ERROR Imdb id not found for La La Land (2016)

**Comment by h3llrais3r** [comment] 2017-12-06 19:32
I've just tried it myself without any issues.
```
2017-12-06 20:30:02,395 DEBUG    [DiskScanner :: autosubliminal.diskscanner] Video file found: Goodbye Berlin (2016).mkv
2017-12-06 20:30:02,401 DEBUG    [DiskScanner :: autosubliminal.diskscanner] Video not found in wanted_items database, start scanning it
2017-12-06 20:30:02,403 DEBUG    [DiskScanner :: autosubliminal.diskscanner] Checking for missing subtitle(s)
2017-12-06 20:30:02,404 DEBUG    [DiskScanner :: autosubliminal.diskscanner] Checking for missing default language
2017-12-06 20:30:02,405 DEBUG    [DiskScanner :: autosubliminal.diskscanner] Video is missing the default language 'nl'
2017-12-06 20:30:02,407 INFO     [DiskScanner :: autosubliminal.fileprocessor] Processing file: Goodbye Berlin (2016).mkv
2017-12-06 20:30:02,410 DEBUG    [DiskScanner :: autosubliminal.fileprocessor] Guessing file info
2017-12-06 20:30:02,775 DEBUG    [DiskScanner :: autosubliminal.fileprocessor] Guess result: MatchesDict([('title', u'Goodbye Berlin'), ('year', 2016), ('container', u'mkv'), ('type', u'movie')])
2017-12-06 20:30:02,778 DEBUG    [DiskScanner :: autosubliminal.fileprocessor] Dict from guess: {'source': None, 'codec': None, 'episode': None, 'quality': None, 'title': u'Goodbye Berlin', 'season': None, 'year': 2016, 'type': u'movie', 'releasegrp': None}
2017-12-06 20:30:02,779 DEBUG    [DiskScanner :: autosubliminal.fileprocessor] Video guessed as movie
2017-12-06 20:30:02,779 DEBUG    [DiskScanner :: autosubliminal.fileprocessor] Enriching dict with metadata
2017-12-06 20:30:02,783 DEBUG    [DiskScanner :: autosubliminal.indexer] Getting imdb info for Goodbye Berlin (2016)
2017-12-06 20:30:24,253 INFO     [DiskScanner :: autosubliminal.indexer] Querying imdb api for Goodbye Berlin (2016)
2017-12-06 20:30:53,226 DEBUG    [DiskScanner :: autosubliminal.indexer] Getting imdb id from api 4911940
2017-12-06 20:30:55,778 INFO     [DiskScanner :: autosubliminal.indexer] Goodbye Berlin (2016) added to cache with 4911940
```

**Comment by h3llrais3r** [comment] 2017-12-06 19:38
Please try with latest develop branch instead of master.

**Comment by Zeusy123** [comment] 2017-12-06 19:40
ok ill delte and reinstall using latest dev branch

**Comment by Zeusy123** [comment] 2017-12-06 20:37
after fresh install etc.. and debug logs enabled heres one didnt find:

Afterburn-Aftershock (2017).mkv


2017-12-06 20:54:33,385 DEBUG    Getting imdb info for Afterburn-Aftershock (2017)
2017-12-06 20:54:34,605 DEBUG    Enriched dict: {'videopath': u'D:\\Ruya\\Current\\Movies Source\\Afterburn-Aftershock (2017)\\Afterburn-Aftershock (2017).mkv', 'season': None, 'releasegrp': None, 'year': 2017, 'quality': None, 'episode': None, 'title': u'Afterburn-Aftershock', 'imdbid': None, 'languages': [], 'source': None, 'codec': None, 'timestamp': u'2017-11-16 10:55:03', 'type': u'movie'}
2017-12-06 20:54:34,608 DEBUG    Checking if the video needs to be skipped

**Comment by Zeusy123** [comment] 2017-12-06 20:41
more: 

Alien Invasion, S.U.M.1 (2017).mkv
Almost Friends (2017).mkv
Bad Idea Gone Wrong, A (2017).mkv

to name just a few:)

**Comment by Zeusy123** [comment] 2017-12-06 20:42
question, why is imdb needed? does subliminal use it or something else?

**Comment by h3llrais3r** [comment] 2017-12-06 20:48
Well it's not really needed (for now). I only search for it to add a link to imdb.

**Comment by Zeusy123** [comment] 2017-12-06 20:50
ah then its not top prority then:)

**Comment by h3llrais3r** [comment] 2017-12-06 20:54
It's your file naming that is the problem.
Since the lookup is done based on the filename, the filename must match the imdb filename.
Searching for `Bad Idea Gone Wrong, A (2017)` will not work but searching for `A Bad Idea Gone Wrong (2017)` does work. So this is not a bug, it's related to your file naming.

**Comment by Zeusy123** [comment] 2017-12-06 21:43
Thanks for the reply, most libraries use the T, T (Y) for movies so you dont have letter T listing all movies beginning with "The" which would be hundreds:)
T, T (Y) puts "The" on the end and "A"

Anyway to ad this check in if imdb not found??
 

For TVseries its just T, T

**Comment by h3llrais3r** [comment] 2017-12-07 08:21
After some thoughts, I came to the conclusion that you are actually not using the tool like you should.
Subliminal, so also Auto-Subliminal, relies on the original release names in order to find the correct subtitle.
Since you are searching for subtitles AFTER you have renamed everything, you'll never get a correct subtitle match, since the source, format, resolution and release group is no longer in your filename.
The same applies for your show/movie names... You'll never find a show which is named as yours, so it's impossible to match it.
This means I won't add checks for non standard naming... If I do that, everyone can ask to support their file naming conventions... 
However, the metadata file is a good alternative. 
So I'll keep this open as feature request.

**Comment by Zeusy123** [comment] 2017-12-07 10:58
Well ive been grabing subs for some time now, and I can say the correct sub is grabbed 90% of the time using just my naming convention:)
All my movies sources if available = 1080p 5.1
Ive done some deep testing/comparing and Im sure if i kept orginal name with res/group etc.. i would get more subs, but as it, it works:)

**Comment by Zeusy123** [comment] 2017-12-08 19:31
also if you decide to impliment reading of the metdata files, they are always giving the full title in the convention your script needs: example:
Folder/file = Christmas Prince, A (2017)
Christmas Prince, A (2017).nfo - contains: 

<LocalTitle>A Christmas Prince</LocalTitle>
<OriginalTitle>A Christmas Prince</OriginalTitle>

Would help with imdb linking??:)

**Comment by h3llrais3r** [comment] 2017-12-08 20:17
Yes that should also contain the original title, but if it also contains the imdb id, no lookup is needed. 😉

**Comment by Zeusy123** [comment] 2017-12-09 10:57
oohh that is true, would save on calls to imdb etc :)

**Comment by yagyeshgod** [comment] 2018-01-14 16:45
I am having the same problem All My movies are showing IMDb id not found error..Is there any fix for it.. I renamed All movies and Tv series using Filebot software...

**Comment by h3llrais3r** [comment] 2018-01-15 07:02
@yagyeshgod Please provide debug logging so I can see how your files are named.
If your files are correctly named, you should not have errors for that.
But as already mentioned above, this doesn't break anything. It's just used to have a link to imdb on the home screen.

**Comment by yagyeshgod** [comment] 2018-01-16 13:04
@h3llrais3r well It is working. When searching a directory with lots of movies it first collect all movies data and then starts downloading the subtitles. I have around 1200 movies and I was able to get around 900 movies subtitles. And I understood what the problem is like Death Race 3: Inferno will not be detected without colon.. the names have to match IMDB names. otherwise very good script thanks alot

**Comment by h3llrais3r** [comment] 2018-01-16 13:25
@yagyeshgod It first scans all the data indeed. Afterwards it searches for the subs.
Nice to hear that it's working fine. 😉

**Comment by yagyeshgod** [comment] 2018-01-16 16:19
sorry for replying late. I am using latest version 2.4.0

**Comment by h3llrais3r** [comment] 2018-01-16 17:17
@yagyeshgod No problem, thanks for replying.
Will check with 'Death Race 3: Inferno' why it's not detected.
Can you send me the actual file name that is processed?

**Comment by yagyeshgod** [comment] 2018-01-16 18:26
Where to find the log file ?? I attached a screenshot. Let me know if u need anything else
![screenshot 3](https://user-images.githubusercontent.com/12203929/35005277-e531b6b2-fb18-11e7-9ce8-1b975ef83e2f.png)

**Comment by h3llrais3r** [comment] 2018-01-16 19:09
Logfile is normally created at same location where of AutoSubliminal.py.
It's called 'autosubliminal.log' by default.
Please also enable debug logging first and rescan. Then I can see all the info.

**Comment by h3llrais3r** [comment] 2018-01-17 21:56
@yagyeshgod I did some changes in the latest development branch which should already increase the imdb matching. (see c2f60050a1c0e1f23bd0e8e70d6505989d0fc5bd)

**Comment by h3llrais3r** [comment] 2019-03-29 18:19
Wont be implemented as there have been a lot of improvements in imdb id lookup.

**Closed by h3llrais3r** 2019-03-29 18:19 UTC
Labels: Feature request
